In [2]:
import numpy as np
import random
from sample_code_submission.model import model
import re

In [3]:
model_dir = "sample_code_submission"
result_dir = 'sample_result_submission/' 
problem_dir = 'ingestion_program/'  
score_dir = 'scoring_program/'

In [4]:
from sys import path; path.append(model_dir); path.append(problem_dir); path.append(score_dir);

In [5]:
data_dir = 'sample_data'

In [7]:
from ingestion_program.data_io import read_as_df
data = read_as_df(data_dir  + '/' + data_name)

ImportError: No module named 'data_converter'

In [5]:
m = model(verbose=True)

In [6]:
m.fit(train_np, gt_np)

Epoch 0, image 0


KeyboardInterrupt: 

In [6]:
pred = m.predict(valid_img_np)

In [9]:
print(pred)
print(pred.shape)
print(valid_img_np.shape[0], valid_img_np.shape[3] * valid_img_np.shape[4])

[[0.64711154 0.64690655 0.65070134 ... 0.64243585 0.6486125  0.64258927]
 [0.64753675 0.64642948 0.6481697  ... 0.64528537 0.65627539 0.64720386]
 [0.65467811 0.65100664 0.65654171 ... 0.64095926 0.6396054  0.64061582]
 [0.64984667 0.64760727 0.65094239 ... 0.64852899 0.64952713 0.64240193]
 [0.64756948 0.6456849  0.64796287 ... 0.64477777 0.65136892 0.64358878]]
(5, 1000000)
5 1000000
